### ISSUE TITLE
Document minimum required rust version

### ISSUE THREAD

**Issue by turboladen** [pest-parser/pest#187]
We're using TeamCity for builds at work; all of our agents were using 1.22.1. After upgrading some crates to use pest 1.0.2, we started getting these build failures. After updating to 1.23.0, the failures went away. Understandable that it's not necessary, but it'd be nice to document what the minimum rust version for pest is.

The failures:

```
[16:44:52][Step 5/7] error[E0599]: no method named `hash` found for type `*const str` in the current scope
[16:44:52][Step 5/7]    --> /home/teamcity/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.2/src/iterators/pair.rs:250:36
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7] 250 |         (self.input as *const str).hash(state);
[16:44:52][Step 5/7]     |                                    ^^^^
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7]     = note: the method `hash` exists but the following trait bounds were not satisfied:
[16:44:52][Step 5/7]             `*const str : std::hash::Hash`
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error[E0599]: no method named `hash` found for type `*const str` in the current scope
[16:44:52][Step 5/7]    --> /home/teamcity/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.2/src/iterators/pairs.rs:162:36
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7] 162 |         (self.input as *const str).hash(state);
[16:44:52][Step 5/7]     |                                    ^^^^
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7]     = note: the method `hash` exists but the following trait bounds were not satisfied:
[16:44:52][Step 5/7]             `*const str : std::hash::Hash`
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
[16:44:52][Step 5/7]    --> /home/teamcity/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.2/src/position.rs:354:23
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7] 354 |                 slice.eq_ignore_ascii_case(string)
[16:44:52][Step 5/7]     |                       ^^^^^^^^^^^^^^^^^^^^
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7]     = help: items from traits can only be used if the trait is in scope
[16:44:52][Step 5/7]     = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
[16:44:52][Step 5/7]             candidate #1: `use std::ascii::AsciiExt;`
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error[E0599]: no method named `hash` found for type `*const str` in the current scope
[16:44:52][Step 5/7]    --> /home/teamcity/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.2/src/position.rs:641:36
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7] 641 |         (self.input as *const str).hash(state);
[16:44:52][Step 5/7]     |                                    ^^^^
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7]     = note: the method `hash` exists but the following trait bounds were not satisfied:
[16:44:52][Step 5/7]             `*const str : std::hash::Hash`
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error[E0599]: no method named `hash` found for type `*const str` in the current scope
[16:44:52][Step 5/7]    --> /home/teamcity/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-1.0.2/src/span.rs:191:36
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7] 191 |         (self.input as *const str).hash(state);
[16:44:52][Step 5/7]     |                                    ^^^^
[16:44:52][Step 5/7]     |
[16:44:52][Step 5/7]     = note: the method `hash` exists but the following trait bounds were not satisfied:
[16:44:52][Step 5/7]             `*const str : std::hash::Hash`
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error: aborting due to 5 previous errors
[16:44:52][Step 5/7] 
[16:44:52][Step 5/7] error: Could not compile `pest`.
[16:44:52][Step 5/7] warning: build failed, waiting for other jobs to finish...
[16:44:55][Step 5/7] error: build failed
```

**Comment by turboladen** [comment]
Thanks! 🎉

**Comment by jeroen** [comment]
What was the last version of this library that would compile on rust 1.22 (ubuntu trusty)?

**Comment by dragostis** [comment]
@jeroen `0.4.1` should work with Rust 1.22, but it is unmaintained. Any reason for the required version? (rustup is easy to install/binaries can easily be distribute to users)

**Comment by jeroen** [comment]
Many users (especially ones that do not have root on their machine) are restricted the the version of rust that is installed with the OS, which is 1.22.

**Comment by dragostis** [comment]
AFAIK, [rustup does not require root](https://github.com/rust-lang-nursery/rustup.rs) since it installs everything in `$HOME/.cargo`.

**Comment by jeroen** [comment]
Perhaps so. Still most linux systems, for example travis-ci, will default to the ubuntu rust 1.22 package that comes with the system. It's a bit annoying that all downstream crates and users are going to have to run a custom rustup just because of pest. I'd like my application to build with ubuntu 1.22 at least.

**Comment by dragostis** [comment]
Using

```yaml
rust:
  - stable
```

on Travis to develop pest which does use rustup and brings Rust's freshest stable to the table. So it doesn't have to be custom. What are you developing?

**Comment by jeroen** [comment]
I'm writing bindings for the R programming language.

**Comment by jeroen** [comment]
Does `rust: stable` on travis also work with another `language:` than rust? Because I need to use `language: r` for my R bindings to build. I'm using rust only as an embedded language, not as the main application.
